### ISSUE TITLE
Which one is considered plagiarism when discovering a project that is completely identical to the current project ?

### ISSUE THREAD

**Issue by xtay573269555** [remvze/moodist#20]
The current: [https://github.com/remvze/moodist](https://github.com/remvze/moodist)

The other: [https://github.com/geekyouth/moodist](https://github.com/geekyouth/moodist)

**Comment by ASafaeirad** [comment]
Just check the git history.

https://github.com/geekyouth/moodist/commits/main/?after=9647f519682aef925ee863b02a7ac2441fb0e865+104

**Comment by remvze** [comment]
Hey there, I'm the original creator of Moodist. To prove it, you can either check the git history of their repo (as @ASafaeirad said), especially the footer component where they have [replaced my name with their own](https://github.com/geekyouth/moodist/commit/b6ab33ab792994bfc46dfa9fc1df51c061d77261#diff-d071bfa9cafe6681c3a640ff509e7f63491cde33f73c7f0de18740d8868050c7), or you can check [the license in their repo](https://github.com/geekyouth/moodist/blob/main/LICENSE), where you can still find my name (i.e., Maze). As for why they have plagiarized my project without even changing the name or the logo, I am still clueless.

**Comment by xtay573269555** [comment]
Ok. I suggest you to report it to github support.

**Comment by giacomocerquone** [comment]
I'm very sorry about this, but the actual problem is that even though he did something awful and disloyal, you @remvze decided to go for a MIT licence for this project, and it's almost obvious this happens sadly.
Quoting your licence file now:

```
to deal in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

And indeed he left a licence with your name in it https://github.com/geekyouth/moodist/blob/main/LICENSE

It sucks, but it happens. It actually happened the same with an old version of my own blog and from that time forward I set the repo private.
